### ISSUE TITLE
relay: move to the RustCrypto 0.11 generation (sha2, hmac, aes-gcm, digest) in one step

### ISSUE THREAD

**Issue by Amakata** [Amakata/sekimore-gw#124]
Dependabot opened #108 (sha2 0.10 → 0.11) and #109 (aes-gcm 0.10 → 0.11) as separate pull requests, and each fails to compile on its own:

```
error[E0277]: the trait bound `CoreWrapper<HmacCore<sha2::Sha256>>: aes_gcm::KeyInit` is not satisfied
error[E0277]: the trait bound `sha2::Sha256: hmac::digest::core_api::CoreProxy` is not satisfied
  --> src/store/crypto.rs
```

`relay/src/store/crypto.rs` derives the KEK with `hmac` over `sha2` and hands it to `aes_gcm` — three crates that share `digest` / `crypto-common` traits. The 0.11 line of RustCrypto moved to `digest` 0.11 / `crypto-common` 0.2, so `sha2`, `hmac`, `aes-gcm` (and `argon2` if it follows) have to move together; one at a time can never build.

Not urgent: no advisory is behind either bump. One pull request, all of them at once, with the store's round-trip tests as the check. Until then Dependabot will keep reopening the pair — a `groups:` entry for the RustCrypto crates in `.github/dependabot.yml` would make it open one instead.

**Comment by Amakata** [comment]
The group works: Dependabot opened #126 with all four (sha2, hmac, aes-gcm, argon2 → 0.11 / 0.13 / 0.11 / 0.6) as one pull request, and it fails to compile as expected — `relay/src/store/crypto.rs` needs the migration. Doing that on top of #126's manifest as one change, after #128 lands (both touch Cargo.lock).
